name: Actions

on:
  pull_request:
    types: [closed]
jobs:
  cleanup-ephemeral-adapters-on-pr-close:
    name: Cleanup Ephemeral Adapters used for testing
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: all
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_SDLC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_SDLC_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.QA_SDLC_AWS_REGION }}
          role-to-assume: ${{ secrets.QA_SDLC_AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.QA_SDLC_KUBECONFIG }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Yarn and setup project
        run: |
          npm install -g yarn
          yarn install
          yarn setup
      - name: cleaning up adapters
        env:
          UNIQUE_NAME: ${{ steps.findPr.outputs.pr }}
        run: |
          # Build the list of adapters using the PR number
          ADAPTER_NAMES=$(kubectl get deployments --namespace adapters | awk '{print $1;}' | grep "${UNIQUE_NAME}$" | awk -F'-' '{print $3;}')
          for adapter in ${ADAPTER_NAMES}; do
            # stop the k6 pod 
            NAME=k6-${UNIQUE_NAME}-${adapter} yarn qa:adapter stop k6 ${UNIQUE_NAME} || true
            # stop the adapter pod
            yarn qa:adapter stop ${adapter} ${UNIQUE_NAME} || true
            # TODO cleanup images created for this test run
          done
