name: Actions

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  run-basic-checks:
    name: Run linters and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn setup
      - run: yarn lint
      - run: yarn test:unit

  test-example:
    needs: [run-basic-checks]
    name: Test example adapter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn setup
      - run: yarn test:example-start-server&
      - run: yarn test:example

  # Read build strategy matrix of adapters, from a json file
  matrix-adapters:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        name: Create job matrix
        id: create-matrix
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/matrix.js`)
            return script()

  build-adapters:
    needs: [run-basic-checks, matrix-adapters]
    name: (${{ matrix.adapter.type }}) Build ${{matrix.adapter.name}} adapter
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-adapters.outputs.adapters)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: ${{ matrix.adapter.cmd }}
      - run: ${{ matrix.adapter.docker }}
