on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
      asset_prefix: ${{ steps.get_asset_prefix.outputs.prefix }}
    # TODO: only if tests pass (needs: [test])
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: yarn
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Get asset prefix
        env:
          TAG_REF_NAME: ${{ github.ref }}
          REPOSITORY_NAME: ${{ github.repository }}
        id: get_asset_prefix
        shell: bash
        run: |
          # eg. github.repository = chainlink/ea, github.ref = release/v0.0.1 -> ea-v0.0.1
          echo ::set-output name=prefix::${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/v}

  # Read build strategy matrix of adapters, from a json file
  matrix-adapters:
    runs-on: ubuntu-latest
    outputs:
      adapters: ${{ steps.set-matrix-adapters.outputs.matrix }}
      adapters-composite: ${{ steps.set-matrix-adapters-composite.outputs.matrix }}
      adapters-synth-index: ${{ steps.set-matrix-adapters-synth-index.outputs.matrix }}
      adapters-2-step: ${{ steps.set-matrix-adapters-2-step.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix-adapters
        run: .github/scripts/set-output-json-matrix .github/strategy/adapters.json
      - id: set-matrix-adapters-composite
        run: .github/scripts/set-output-json-matrix .github/strategy/adapters-composite.json
      - id: set-matrix-adapters-synth-index
        run: .github/scripts/set-output-json-matrix .github/strategy/adapters-synth-index.json
      - id: set-matrix-adapters-2-step
        run: .github/scripts/set-output-json-matrix .github/strategy/adapters-2-step.json

  publish-artifacts:
    needs: [release, matrix-adapters]
    runs-on: ubuntu-latest
    name: Publish ${{ matrix.adapter }} adapter zip (GitHub Release)
    strategy:
      matrix: ${{fromJson(needs.matrix-adapters.outputs.adapters)}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make zip adapter=${{ matrix.adapter }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./${{ matrix.adapter }}/dist/${{ matrix.adapter }}-adapter.zip
          asset_name: ${{ needs.release.outputs.asset_prefix }}-${{ matrix.adapter }}-adapter.zip
          asset_content_type: application/zip

  publish-composite-artifacts:
    needs: [release, matrix-adapters]
    runs-on: ubuntu-latest
    name: Publish composite ${{ matrix.adapter }} adapter zip (GitHub Release)
    strategy:
      matrix: ${{fromJson(needs.matrix-adapters.outputs.adapters-composite)}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make zip adapter=composite/${{ matrix.adapter }} name=${{ matrix.adapter }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./composite/${{ matrix.adapter }}/dist/${{ matrix.adapter }}-adapter.zip
          asset_name: ${{ needs.release.outputs.asset_prefix }}-${{ matrix.adapter }}-adapter.zip
          asset_content_type: application/zip

  publish-synth-index-artifacts:
    needs: [release, matrix-adapters]
    name: Publish synth-index ${{ matrix.adapter }} adapter zip (GitHub Release)
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-adapters.outputs.adapters-synth-index)}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make zip-synth-index adapter=${{ matrix.adapter }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./synth-index/${{ matrix.adapter }}/dist/synth-index-${{ matrix.adapter }}-adapter.zip
          asset_name: ${{ needs.release.outputs.asset_prefix }}-synth-index-${{ matrix.adapter }}-adapter.zip
          asset_content_type: application/zip

  publish-2-step-artifacts:
    needs: [release, matrix-adapters]
    name: Publish 2-step ${{ matrix.adapter }} adapter zip (GitHub Release)
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-adapters.outputs.adapters-2-step)}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make zip-2-step adapter=${{ matrix.adapter }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./2-step/${{ matrix.adapter }}/dist/${{ matrix.adapter }}-2-step-adapter.zip
          asset_name: ${{ needs.release.outputs.asset_prefix }}-${{ matrix.adapter }}-2-step-adapter.zip
          asset_content_type: application/zip
